"""create folder

Revision ID: 4ae699b89968
Revises: 
Create Date: 2020-06-18 18:00:28.887308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae699b89968'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('phone_no', sa.String(length=12), nullable=False),
    sa.Column('msg', sa.String(length=120), nullable=False),
    sa.Column('date', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('sno')
    )
    op.create_table('posts',
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=25), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=False),
    sa.Column('tagline', sa.String(length=120), nullable=False),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.Column('img_file', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('sno'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
