
# tasks file for ./roles/docker/
- name: Create a test directory if it does not exist
  file:
    path: "{{ansible_user_dir }}/test"
    state: directory
    mode: '0755'

- name: Copy Dockerfile
  copy:
    src: Dockerfile
    dest: "{{ansible_user_dir }}/test/"

- name: Copy Blogger.zip
  copy:
    src: Blogger.zip
    dest: "{{ansible_user_dir }}/test/"
    
- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: "{{ansible_user_dir }}/test/Blogger.zip"
    dest: "{{ansible_user_dir }}/test/"
    remote_src: yes
  
- name: Execute the command to build docker image
  shell: docker build -t blog:10 '{{ ansible_user_dir }}/test/.'

- include_tasks: docker-swarm-service.yml
# - include_tasks: docker-container.yml
